{% set name = "cattrs" %}
{% set version = "24.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cattrs-{{ version }}.tar.gz
  sha256: 8028cfe1ff5382df59dd36474a86e02d817b06eaf8af84555441bac915d2ef85

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<38]

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python
    - attrs >=23.1.0
    - exceptiongroup >=1.1.1            # [py<311]
    - typing_extensions >=4.1.0,!=4.6.3 # [py<311]

test:
  imports:
    - cattr
    - cattr.converters
    - cattr.preconf
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/python-attrs/cattrs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Complex custom class converters for attrs.'
  description: |
    cattrs is an open source Python library for structuring and unstructuring data.
    cattrs works best with attrs classes and the usual Python collections, but other
    kinds of classes are supported by manually registering converters.
  dev_url: https://github.com/python-attrs/cattrs
  doc_url: https://catt.rs/

extra:
  recipe-maintainers:
    - aldanor
    - Tinche
