{% set name = "cattrs" %}
{% set version = "23.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/python-attrs/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9dbc7359c1ac2acdd011607218fd2aac26aab5fdaa51a7e162110d029e277ff3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
    - poetry-core >=1.1.0
  run:
    - python
    - attrs >=20
    - exceptiongroup             # [py<311]
    - typing_extensions >=4.1.0  # [py<311]
  run_constrained:
    - ujson >=5.4.0,<6
    - orjson >=3.5.2,<4
    - msgpack >=1.0.2,<2
    - PyYAML >=6.0,<7
    - tomlkit  >=0.11.4,<1
    - cbor2 >=5.4.6,<6
    - pymongo >=4.2.0,<5

test:
  imports:
    - cattr
    - cattr.converters
    - cattr.preconf
  requires:
    - pip
    - pytest
    - hypothesis >=6.79.4
    - typing-extensions >=4.7.1
  source_files:
    - tests
  commands:
    - pip check
    # ignore:
    #   test_unstructure_collections.py because it requires immutables>=0.20 (unavailable)
    #   test_preconf.py     because it requires bson (optional dependency)
    #   test_typeddicts.py  because of https://github.com/python-attrs/cattrs/issues/439
    #                       reenable it on 23.2.0
    - pytest -v tests --ignore=tests/test_unstructure_collections.py --ignore=tests/test_preconf.py --ignore=tests/test_typeddicts.py

about:
  home: https://github.com/python-attrs/cattrs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Complex custom class converters for attrs.'
  description: |
    cattrs is an open source Python library for structuring and unstructuring data.
    cattrs works best with attrs classes and the usual Python collections, but other
    kinds of classes are supported by manually registering converters.
  dev_url: https://github.com/python-attrs/cattrs
  doc_url: https://catt.rs/

extra:
  recipe-maintainers:
    - aldanor
    - Tinche
