{% set name = "cattrs" %}
{% set version = "26.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3cf49f69df8326bcf17a3cb3d3d3ec4a856858fe3a7473746c9044c317d3ba55

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python
    - attrs >=25.4.0
    - typing_extensions >=4.14.0
    - exceptiongroup >=1.1.1  # [py<311]
  run_constrained:
    - ujson >=5.10.0
    - orjson >=3.11.3  # [python_impl == CPython]
    - msgpack-python >=1.0.5
    - pyyaml >=6.0
    - tomlkit >=0.11.8
    - cbor2 >=5.4.6
    - pymongo >=4.4.0
    - msgspec >=0.21.1  # [python_impl == CPython]
    - tomli >=1.1.0  # [py<311]
    - tomli-w >=1.1.0

# E   ModuleNotFoundError: No module named 'bson'
{% set ignore_tests = "--ignore=tests/preconf/test_pyyaml.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_preconf.py" %}

test:
  source_files:
    - tests
  imports:
    - cattr
    - cattrs
    - cattrs._compat
    - cattrs._generics
    - cattrs.cols
    - cattrs.converters
    - cattrs.disambiguators
    - cattrs.dispatch
    - cattrs.errors
    - cattrs.fns
    - cattrs.gen
    - cattrs.preconf
    - cattrs.strategies
  requires:
    - pip
    - pytest
    - hypothesis
    - immutables
    - pyyaml >=6.0
    - msgspec >=0.21.1
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv tests {{ ignore_tests }}

about:
  home: https://github.com/python-attrs/cattrs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Complex custom class converters for attrs.
  description: |
    cattrs is an open source Python library for structuring and unstructuring data.
    cattrs works best with attrs classes and the usual Python collections, but other
    kinds of classes are supported by manually registering converters.
  dev_url: https://github.com/python-attrs/cattrs
  doc_url: https://catt.rs

extra:
  recipe-maintainers:
    - aldanor
    - Tinche
