{% set name = "cattrs" %}
{% set version = "25.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cattrs-{{ version }}.tar.gz
  sha256: 1ac88d9e5eda10436c4517e390a4142d88638fe682c436c93db7ce4a277b884a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python
    - attrs >=25.4.0
    - exceptiongroup >=1.1.1  # [py<311]
    - typing_extensions >=4.14.0
  run_constrained:
    - pymongo >=4.4.0
    - cbor2 >=5.4.6
    - msgpack-python >=1.0.5
    - PyYAML >=6.0
    - tomlkit >=0.11.8
    - ujson >=5.10.0

test:
  imports:
    - cattr
    - cattr.converters
    - cattr.preconf
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/python-attrs/cattrs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Complex custom class converters for attrs.
  description: |
    cattrs is an open source Python library for structuring and unstructuring data.
    cattrs works best with attrs classes and the usual Python collections, but other
    kinds of classes are supported by manually registering converters.
  dev_url: https://github.com/python-attrs/cattrs
  doc_url: https://catt.rs/

extra:
  recipe-maintainers:
    - aldanor
    - Tinche
