travis:
  secure:
    BINSTAR_TOKEN: YSIvXhxTiAFtIpgOLvel07tUl5VKifwclJ6EPzit8iUPiwusDo6Lb+Dk3rrxXvTyrZomXzEQuZjI5edWYfLwbkOha/1Vb/EYU8sUcleXqzqCKuGejw8pS8RcaX/zIFAPL4oqCKclmOPRdB37cn3SQKpbjPFfKVmvTOFSfdBsgqdrpJKoH9CizfUlBmuajOIuBVJLy0r6lDNG8D2uoWtlmaIkiyYTYNE+QV07y8bAUMAxaX9dkhHFhKpAyXGrkfOjvMZYzxRsV1WkW9EW6zM0CFzBcS862LbBT3O0Z9v1eJUcIay6lo4QG3BFal9GhFSkGpch/+T0Ni7xTXX+BfbDEI1jncOwXf7JPnDonYpDRCg/G+LRDS7shT5kc+zwoaF98bYoMaq4IlyJokyRptD9xZI7BDRiKIYzqNCfyBckhxdpewYJSDK2gnMocq8slVqN2i9HzZoEMZyc7GSbBgDARrtu3oOxk/jv3wp19jmpativFmvm2eROb2efFpL6L9WnTLqKfagQ/xai16/JxRKgREDQ6ipakqQnd8OrKFIBQOCWyom6nPrGG5GSZNDFrtr5xjl5yGqwJv2P/GyXu36Pis2q332YFMc3D4r3wFezDhWhWV9NcZN716yBjVAyjqY85IL+JFJyDheZu5tr4J162Oqvd0emngHRoBs0sK+vDUU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
